# Generated by Django 5.0.8 on 2024-08-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0002_blogdetail'),
        ('images', '0002_alter_customrendition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
