# Generated by Django 5.0.8 on 2024-08-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0004_blogpagetags_blogdetail_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='body',
        ),
    ]
