# Generated by Django 5.0.8 on 2024-08-18 01:02

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0007_alter_blogdetail_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authoer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('image', 0), ('doc', 1), ('page', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 2: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False})}, null=True),
        ),
    ]
