# Generated by Django 5.0.8 on 2024-08-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0008_authoer_alter_blogdetail_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authoer',
            new_name='Author',
        ),
    ]
