# Generated by Django 5.0.8 on 2024-08-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0011_author_expire_at_author_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpages.author'),
        ),
    ]
