# Generated by Django 5.0.8 on 2024-08-18 23:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0013_author_locked_author_locked_at_author_locked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
