# Generated by Django 5.0.8 on 2024-08-19 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0015_alter_blogdetail_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_edit_autor_name', 'Can edit author name')]},
        ),
        migrations.AddField(
            model_name='author',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='author',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
