# Generated by Django 5.0.8 on 2024-08-19 03:30

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0016_alter_author_options_author_locale_and_more'),
    ]

    operations = [
        BootstrapTranslatableModel('blogpages.Author'),
    ]
