# Generated by Django 5.0.8 on 2024-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepagegalleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
