# Generated by Django 5.0.8 on 2024-08-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepagegalleryimage_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagegalleryimage',
            name='caption',
        ),
    ]
